---
- name: Vector | Download packages
  ansible.builtin.get_url:
    url: "{{ vector_url_deb if ansible_distribution == 'Ubuntu' else vector_url_rpm }}"
    dest: "{{ vector_download_dest }}"

- name: Install Vector on Debian
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    deb: "{{ vector_download_dest }}"
    update_cache: yes
    force: yes

- name: Install Vector on CentOS
  when: ansible_distribution == 'CentOS'
  ansible.builtin.yum:
    name: "{{ vector_download_dest }}"
    state: present
    disable_gpg_check: true
