---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: quay.io/pycontribs/centos:stream8
    pre_build_image: true
  - name: ubuntu
    image: pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
